name: studio_projects
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  http: ^1.6.0
  flutter_easyloading: ^3.0.5
  flutter_secure_storage: ^10.0.0
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

#  fonts:
#    - family: Schyler
#      fonts:
#        - asset: fonts/Schyler-Regular.ttf
#        - asset: fonts/Schyler-Italic.ttf
#          style: italic
#
#    - family: Trajan Pro
#      fonts:
#        - asset: fonts/TrajanPro.ttf
#        - asset: fonts/TrajanPro_Bold.ttf
#          weight: 700
